version: '3'
 
services:
  jenkins:
    container_name: 'jenkins-containerPE03'
    privileged: true
    build: .
    ports:
      - '9090:8080'
      - '50000:50000'
    volumes:      
      - ./jenkins-data:/var/jenkins_homePE03
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
 
volumes:
  myjenkins: